### PR TITLE
Fixed crash of config portal when connected to a configured WiFi

### PR DESCRIPTION
**Pull request by mwick83**
Using local copies of IP address and SSID string fixes this. Also fixed indentation and streamlined debug + display output.

### CODE REVIEW

**Comment by marcelstoer** [comment]
Thanks but the commit history is a bit of a mess. It's hard to see what actually constitutes this PR as it contains other changes. Could you please rebase and squash?

**Comment by mwick83** [comment]
I'll see if I find time this weekend!

**Comment by marcelstoer** [comment]
That would be awesome, thanks.

**Comment by marcelstoer** [comment]
This stalled and the Wunderground app was replaced -> closing

**Pull request closed without merging**
