### PR TITLE
fix wifi signal strength display

### PR DESCRIPTION
**Pull request by mikecarlton**
Here's a PR to show WiFi signal strength.  The basic code was present, but it was not called and would display in wrong place.

### CODE REVIEW

**Comment by gsemet** [comment]
works great! I put mine with a slight offset
```
        ...
        gfx.setPixel(SCREEN_WIDTH / 2 + 35 + 2 * i, 8 - j);
  ...
  gfx.drawString(SCREEN_WIDTH / 2 + 45, -1, String(quality) + "%");
```

**Comment by marcelstoer** [comment]
Nice, I like that! 

> The basic code was present, but it was not called

@squix78 do you remember why you never activated this? Simply lack of time?

I prefer @gsemet's version with the offset. @mikecarlton if you were to rebase onto current `master` to resolve the conflicts we could merge this PR and give you proper credit (rather than just commit the code ourselves). Interested?

**Comment by mikecarlton** [comment]
@marcelstoer -- i'd be happy to rebase and update this pr.  Will take me a day or two to get to it.

**Comment by marcelstoer** [comment]
Cool, looking forward to it, thanks.

**Comment by marcelstoer** [comment]
Thanks, looks nice!

**Pull request merged**
